[package]
name = "test1"
version = "0.1.0"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.6.3"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.12.0" }

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.22.0" }


[[target.starknet-contract]]
build-external-contracts = [
    "openzeppelin::account::account::Account",
    "openzeppelin::token::erc20::{ERC20Component, ERC20HooksEmptyImpl}",
    ]
casm = false
sierra = true
